var challenges = {
  html: [
    {
      title: "Dis Bonjour au Monde !",
      desc: "Chaque programmeur commence par là. Écris un grand titre qui dit 'Bonjour le Monde !' en utilisant la balise <h1>.",
      hint: `<h1>Bonjour le Monde !</h1>`,
      filename: "index.html",
      starter: `<!-- Écris ton titre ici -->\n`,
      check: (code) => /<h1[^>]*>\s*Bonjour\s*le\s*Monde\s*!?\s*<\/h1>/i.test(code), //boolean
      preview: true,
    },
    {
      title: "Une Belle Couleur",
      desc: "Fais un paragraphe qui dit 'J'adore le CSS !' et donne-lui la couleur bleue avec l'attribut style.",
      hint: `<p style="color: blue;">J'adore le CSS !</p>`,
      filename: "index.html",
      starter: `<!-- Ton paragraphe coloré ici -->\n`,
      check: (code) => /<p[^>]*style[^>]*color\s*:\s*blue[^>]*>/i.test(code),
      preview: true,
    },
    {
      title: "Clique ici !",
      desc: "Crée un bouton qui dit 'Clique moi !' et qui affiche une alerte avec le message 'Bravo !' quand on clique dessus.",
      hint: `<button onclick="alert('Bravo !')">Clique moi !</button>`,
      filename: "index.html",
      starter: `<!-- Ton bouton ici -->\n`,
      check: (code) => /<button[^>]*onclick[^>]*alert[^>]*>.*Clique moi.*<\/button>/i.test(code),
      preview: true,
    },
    {
      title: "Une Liste de Courses",
      desc: "Crée une liste non ordonnée <ul> avec 3 aliments dedans. Chaque aliment doit être dans une balise <li>.",
      hint: `<ul>\n  <li>Pain</li>\n  <li>Lait</li>\n  <li>Oeufs</li>\n</ul>`,
      filename: "index.html",
      starter: `<!-- Ta liste ici -->\n`,
      check: (code) => /<ul>/i.test(code) && (code.match(/<li>/gi) || []).length >= 3,
      preview: true,
    },
    {
      title: "Une Image",
      desc: "Ajoute une image avec la balise <img>. Utilise n'importe quelle URL pour src et donne-lui un alt qui décrit l'image.",
      hint: `<img src="https://placekitten.com/200/200" alt="Un chaton mignon">`,
      filename: "index.html",
      starter: `<!-- Ton image ici -->\n`,
      check: (code) => /<img[^>]*src=["'][^"']+["'][^>]*alt=["'][^"']+["'][^>]*>/i.test(code),
      preview: true,
    },
  ],

  js: [
    {
      title: "Ta Première Variable",
      desc: "Crée une variable 'prenom' et mets-y ton prénom. Ensuite utilise console.log() pour afficher : 'Je m'appelle [prénom]'",
      hint: `let prenom = "Alice";\nconsole.log("Je m'appelle " + prenom);`,
      filename: "script.js",
      starter: `// Crée ta variable ici\n`,
      check: (code) => /let\s+prenom\s*=/.test(code) && /console\.log/.test(code),
      preview: false,
    },
    {
      title: "Pair ou Impair ?",
      desc: "Crée une variable 'nombre' avec la valeur 7. Utilise le modulo (%) pour vérifier si ce nombre est pair ou impair et affiche le résultat.",
      hint: `let nombre = 7;\nif (nombre % 2 === 0) {\n  console.log("Pair");\n} else {\n  console.log("Impair");\n}`,
      filename: "script.js",
      starter: `let nombre = 7;\n\n// Vérifie si pair ou impair\n`,
      check: (code) => /nombre\s*%\s*2/.test(code) && /if\s*\(/.test(code) && /console\.log/.test(code),
      preview: false,
    },
    {
      title: "La Table de Multiplication",
      desc: "Utilise une boucle for pour afficher la table de multiplication de 3 (de 3x1 jusqu'à 3x10).",
      hint: `for (let i = 1; i <= 10; i++) {\n  console.log("3 x " + i + " = " + (3 * i));\n}`,
      filename: "script.js",
      starter: `// Ta boucle ici\n`,
      check: (code) => /for\s*\(/.test(code) && /console\.log/.test(code) && /3\s*\*\s*i|i\s*\*\s*3/.test(code),
      preview: false,
    },
    {
      title: "Une Fonction Magique",
      desc: "Crée une fonction 'addition' qui prend deux paramètres a et b, et retourne leur somme. Appelle-la avec 5 et 3 et affiche le résultat.",
      hint: `function addition(a, b) {\n  return a + b;\n}\nconsole.log(addition(5, 3));`,
      filename: "script.js",
      starter: `// Ta fonction ici\n`,
      check: (code) => /function\s+addition\s*\(/.test(code) && /return\s+a\s*\+\s*b/.test(code) && /console\.log/.test(code),
      preview: false,
    },
    {
      title: "Compte à Rebours",
      desc: "Fais un compte à rebours de 10 jusqu'à 0 avec une boucle. Affiche chaque nombre, et quand tu arrives à 0, affiche 'Décollage ! 🚀'",
      hint: `for (let i = 10; i >= 0; i--) {\n  if (i === 0) {\n    console.log("Décollage ! 🚀");\n  } else {\n    console.log(i);\n  }\n}`,
      filename: "script.js",
      starter: `// Ton compte à rebours ici\n`,
      check: (code) => /for\s*\(/.test(code) && /i--/.test(code) && /console\.log/.test(code),
      preview: false,
    },
  ],

  python: [
    {
      title: "Affiche ton Prénom !",
      desc: "Utilise print() pour afficher ton prénom. Simple mais essentiel — c'est comme ça que Python parle !",
      hint: `print("Alice")`,
      filename: "main.py",
      starter: `# Affiche ton prénom ici\n`,
      check: (code) => /print\s*\(\s*["'].+["']\s*\)/.test(code),
      preview: false,
    },
    {
      title: "T'as 18 ans ?",
      desc: "Crée une variable 'age', puis utilise if/else pour afficher True si l'âge est supérieur ou égal à 18, False sinon.",
      hint: `age = 21\nif age >= 18:\n    print(True)\nelse:\n    print(False)`,
      filename: "main.py",
      starter: `# Crée la variable age et vérifie\n`,
      check: (code) => /age\s*=\s*\d+/.test(code) && /if\s+age/.test(code) && /else/.test(code) && /print\s*\(/.test(code),
      preview: false,
    },
    {
      title: "La Somme d'une Liste",
      desc: "Crée une liste 'notes' avec 5 notes d'élève. Calcule et affiche la moyenne de ces notes en utilisant sum.",
      hint: `notes = [12, 15, 9, 18, 14]\nmoyenne = sum(notes) / len(notes)\nprint(moyenne)`,
      filename: "main.py",
      starter: `# Ta liste de notes ici\n`,
      check: (code) => /\w+\s*=\s*\[/.test(code) && /sum\s*\(/.test(code) && /len\s*\(/.test(code) && /print\s*\(/.test(code),
      preview: false,
    },
    {
      title: "FizzBuzz",
      desc: "Le classique ! Pour chaque nombre de 1 à 20 : affiche 'Fizz' si divisible par 3, 'Buzz' si par 5, 'FizzBuzz' si les deux, sinon le nombre.",
      hint: `for i in range(1, 21):\n    if i % 15 == 0:\n        print("FizzBuzz")\n    elif i % 3 == 0:\n        print("Fizz")\n    elif i % 5 == 0:\n        print("Buzz")\n    else:\n        print(i)`,
      filename: "main.py",
      starter: `# FizzBuzz de 1 à 20\n`,
      check: (code) => /for\s+\w+\s+in\s+range/.test(code) && /Fizz/.test(code) && /Buzz/.test(code) && /%\s*3/.test(code) && /%\s*5/.test(code),
      preview: false,
    },
    {
      title: "Devine le Nombre",
      desc: "Crée une fonction 'devine' qui prend un nombre en paramètre. Si c'est 7, affiche 'Bravo !', sinon affiche 'Raté !'. Appelle-la avec 7 puis avec 3.",
      hint: `def devine(nombre):\n    if nombre == 7:\n        print("Bravo !")\n    else:\n        print("Raté !")\n\ndevine(7)\ndevine(3)`,
      filename: "main.py",
      starter: `# Ta fonction devine() ici\n`,
      check: (code) => /def\s+devine\s*\(/.test(code) && /if/.test(code) && /print\s*\(/.test(code) && /devine\s*\(\s*7\s*\)/.test(code),
      preview: false,
    },
  ],
};