var challenges = {
  html: [
    {
      title: "Say Hello to the World!",
      desc: "Every programmer's first step. Write a big heading that says 'Hello World!' using an HTML tag. The tag for headings is <h1>.",
      hint: `<h1>Hello World!</h1>`,
      filename: "index.html",
      starter: `<!-- Write your heading below! -->\n`,
      check: (code) => /<h1[^>]*>\s*Hello\s*World\s*!?\s*<\/h1>/i.test(code),
      preview: true,
    },
    {
      title: "Painting with Color",
      desc: "Make a paragraph that says 'I love CSS!' and give it a red color using the style attribute.",
      hint: `<p style="color: red;">I love CSS!</p>`,
      filename: "index.html",
      starter: `<!-- Add a colored paragraph below -->\n`,
      check: (code) => /<p[^>]*style[^>]*color\s*:\s*red[^>]*>.*I love CSS.*<\/p>/i.test(code),
      preview: true,
    },
    {
      title: "Click me!",
      desc: "Create a button that says 'Click me!' and shows an alert saying 'Hello!' when clicked.",
      hint: `<button onclick="alert('Hello!')">Click me!</button>`,
      filename: "index.html",
      starter: `<!-- Your button here -->\n`,
      check: (code) => /<button[^>]*onclick[^>]*>.*Click me.*<\/button>/i.test(code),
      preview: true,
    },
    {
      title: "A Shopping List",
      desc: "Create an unordered list <ul> with 3 food items inside. Each item must be in a <li> tag.",
      hint: `<ul>\n  <li>Bread</li>\n  <li>Milk</li>\n  <li>Eggs</li>\n</ul>`,
      filename: "index.html",
      starter: `<!-- Your list here -->\n`,
      check: (code) => /<ul>/i.test(code) && (code.match(/<li>/gi) || []).length >= 3,
      preview: true,
    },
    {
      title: "Add an Image",
      desc: "Add an image with the <img> tag. Use any URL for src and give it an alt that describes the image.",
      hint: `<img src="https://placekitten.com/200/200" alt="A cute kitten">`,
      filename: "index.html",
      starter: `<!-- Your image here -->\n`,
      check: (code) => /<img[^>]*src=["'][^"']+["'][^>]*alt=["'][^"']+["'][^>]*>/i.test(code),
      preview: true,
    },
  ],

  js: [
    {
      title: "Your First Variable",
      desc: "Create a variable called 'name' and set it to your name. Then use console.log() to print: 'My name is [name]'",
      hint: `let name = "Alice";\nconsole.log("My name is " + name);`,
      filename: "script.js",
      starter: `// Create your variable here\n`,
      check: (code) => /let\s+name\s*=/.test(code) && /console\.log/.test(code),
      preview: false,
    },
    {
      title: "Even or Odd?",
      desc: "Create a variable 'number' with the value 7. Use modulo (%) to check if it's even or odd and print the result.",
      hint: `let number = 7;\nif (number % 2 === 0) {\n  console.log("Even");\n} else {\n  console.log("Odd");\n}`,
      filename: "script.js",
      starter: `let number = 7;\n\n// Check if even or odd\n`,
      check: (code) => /number\s*%\s*2|nombre\s*%\s*2/.test(code) && /if\s*\(/.test(code) && /console\.log/.test(code),
      preview: false,
    },
    {
      title: "Multiplication Table",
      desc: "Use a for loop to print the multiplication table of 3 (from 3x1 to 3x10).",
      hint: `for (let i = 1; i <= 10; i++) {\n  console.log("3 x " + i + " = " + (3 * i));\n}`,
      filename: "script.js",
      starter: `// Your loop here\n`,
      check: (code) => /for\s*\(/.test(code) && /console\.log/.test(code) && /3\s*\*\s*i|i\s*\*\s*3/.test(code),
      preview: false,
    },
    {
      title: "A Magic Function",
      desc: "Create a function 'addition' that takes two parameters a and b, and returns their sum. Call it with 5 and 3 and print the result.",
      hint: `function addition(a, b) {\n  return a + b;\n}\nconsole.log(addition(5, 3));`,
      filename: "script.js",
      starter: `// Your function here\n`,
      check: (code) => /function\s+addition\s*\(/.test(code) && /return\s+a\s*\+\s*b/.test(code) && /console\.log/.test(code),
      preview: false,
    },
    {
      title: "Countdown",
      desc: "Make a countdown from 10 to 0 with a loop. Print each number, and when you reach 0, print 'Liftoff! 🚀'",
      hint: `for (let i = 10; i >= 0; i--) {\n  if (i === 0) {\n    console.log("Liftoff! 🚀");\n  } else {\n    console.log(i);\n  }\n}`,
      filename: "script.js",
      starter: `// Your countdown here\n`,
      check: (code) => /for\s*\(/.test(code) && /i--/.test(code) && /console\.log/.test(code),
      preview: false,
    },
  ],

  python: [
    {
      title: "Print it out!",
      desc: "Python's version of Hello World is just one line! Use the print() function to display 'Hello, World!'",
      hint: `print("Hello, World!")`,
      filename: "main.py",
      starter: `# Write your print statement here\n`,
      check: (code) => /print\s*\(\s*["']Hello,?\s*World!?["']\s*\)/i.test(code),
      preview: false,
    },
    {
      title: "Are you 18?",
      desc: "Create a variable 'age', then use if/else to print True if age is 18 or more, False otherwise.",
      hint: `age = 21\nif age >= 18:\n    print(True)\nelse:\n    print(False)`,
      filename: "main.py",
      starter: `# Create the age variable and check\n`,
      check: (code) => /age\s*=\s*\d+/.test(code) && /if\s+age/.test(code) && /else/.test(code) && /print\s*\(/.test(code),
      preview: false,
    },
    {
      title: "List Average",
      desc: "Create a list 'grades' with 5 numbers. Calculate and print the average of these grades.",
      hint: `grades = [12, 15, 9, 18, 14]\naverage = sum(grades) / len(grades)\nprint(average)`,
      filename: "main.py",
      starter: `# Your list of grades here\n`,
      check: (code) => /\w+\s*=\s*\[/.test(code) && /sum\s*\(/.test(code) && /len\s*\(/.test(code) && /print\s*\(/.test(code),
      preview: false,
    },
    {
      title: "FizzBuzz",
      desc: "The classic! For each number from 1 to 20: print 'Fizz' if divisible by 3, 'Buzz' if by 5, 'FizzBuzz' if both, otherwise the number.",
      hint: `for i in range(1, 21):\n    if i % 15 == 0:\n        print("FizzBuzz")\n    elif i % 3 == 0:\n        print("Fizz")\n    elif i % 5 == 0:\n        print("Buzz")\n    else:\n        print(i)`,
      filename: "main.py",
      starter: `# FizzBuzz from 1 to 20\n`,
      check: (code) => /for\s+\w+\s+in\s+range/.test(code) && /Fizz/.test(code) && /Buzz/.test(code) && /%\s*3/.test(code) && /%\s*5/.test(code),
      preview: false,
    },
    {
      title: "Guess the Number",
      desc: "Create a function 'guess' that takes a number. If it's 7, print 'Correct!', otherwise print 'Wrong!'. Call it with 7 and then 3.",
      hint: `def guess(number):\n    if number == 7:\n        print("Correct!")\n    else:\n        print("Wrong!")\n\nguess(7)\nguess(3)`,
      filename: "main.py",
      starter: `# Your guess() function here\n`,
      check: (code) => /def\s+guess\s*\(/.test(code) && /if/.test(code) && /print\s*\(/.test(code) && /guess\s*\(\s*7\s*\)/.test(code),
      preview: false,
    },
  ],
};